name: GitHub Issues - auto-comment on issues [WIP]

on: workflow_dispatch
  
jobs:
  test-issue-comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'

    - name: Install
      run: yarn --frozen-lockfile

    - name: Add release comments to issues and PRs
      uses: actions/github-script@v7
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          script: |
            const { default: addIssueComments } = await import('${{ github.workspace }}/.github/createIssueComments.mjs');

            await addIssueComments({ github, context })
