name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Build packages
      run: yarn build

    - name: Publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
          git config user.email ${{ secrets.NPM_EMAIL }}
          git config user.name ${{ secrets.NPM_USER }}
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          ${GITHUB_WORKSPACE}/node_modules/.bin/lerna publish "0.0.0-${git_hash}" \
            --exact \
            --no-push \
            --no-git-tag-version \
            --pre-dist-tag dev