name: Publish

on: push
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install
      run: yarn

    - name: Build
      run: cd packages/main && yarn build

    - name: Auth
      run: npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # - name: Main package
    #   run: cd packages/main

    - name: Make prerelease to npm
      uses: epeli/npm-release@v1
      with:
        type: prerelease
        token: ${{ secrets.NPM_TOKEN }}

    # - name: Fiori package
    #   run: cd ../fiori

    # - name: Make prerelease to npm
    #   uses: epeli/npm-release@v1
    #   with:
    #     type: prerelease
    #     token: ${{ secrets.NPM_TOKEN }}