name: Release Preview

on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Build packages
      run: yarn build

      - name: NPM Registry
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > packages/base/.npmrc
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > packages/main/.npmrc
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > packages/fiori/.npmrc

    - name: Publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
          git config user.email ${{ secrets.NPM_EMAIL }}
          git config user.name ${{ secrets.NPM_USER }}
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git checkout main
          ${GITHUB_WORKSPACE}/node_modules/.bin/lerna publish "0.0.0-${git_hash}"  --no-verify-access \
            --exact \
            --no-push \
            --no-git-tag-version \
            --pre-dist-tag dev
