name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    if: "contains(github.event.head_commit.message, 'prerelease')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn

    - name: Build packages
      run: yarn build

    - name: Auth
      run: npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to npm
      env:
        NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
          git config user.email ${{ secrets.NPM_EMAIL }}
          git config user.name ${{ secrets.NPM_USERNAME }}
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          current_branch=$(node -p -e "'${{ github.ref }}'.replace('refs/heads/', '')")
          ${GITHUB_WORKSPACE}/node_modules/.bin/lerna publish "0.0.0-${git_hash}" \
            --exact \
            --no-push \
            --no-git-tag-version \
            --pre-dist-tag dev \
            --allow-branch ${current_branch}