name: Create Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          token: ${{ secrets.GH_TOKEN }}
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Publish
      run: |
        npm config set //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        yarn lerna version ${{ env.RELEASE_VERSION }} --conventional-commits --yes --create-release github 
        yarn lerna publish from-git --yes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}