name: Release-on-push

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Publish
      run: |
          yarn config set https://registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
          git config user.email ${{ secrets.GIT_EMAIL }}
          git config user.name ${{ secrets.GIT_NAME }}
          npx lerna version --conventional-commits --conventional-graduate --yes
          npx lerna publish from-git --yes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
