name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'     
        required: true
      tag:
          description: 'Tag'     
          required: true
          default: latest

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install
      run: yarn

    - name: Build
      run: yarn build

    - name: Publish
      env:
        NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        node ./.github/actions/release.js --version=${{ github.event.inputs.version }} --tag=${{ github.event.inputs.tag }}
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
        yarn lerna version ${{ github.event.inputs.version }} --exact --conventional-prerelease --force-publish --yes --create-release github 
